version: '3.9'
services:
  mongo_db:
  # MongoDB Services
      container_name: mongodb_container
      image: mongo:latest
      restart: always
      ports:
        - 2717:27017
      volumes: 
      - mongo_db:/data/db

# Nestjs Service
  api:
    image: nestjs-dockerized
    build: .
    ports:
      - 3000:5000
    volumes:
      - .:/usr/src/app
    environment:
       PORT: 3000
       MONGODB_URI: mongodb://mongo_db:27017
       DB_NAME: nestjs-reign-service-app
       NAME: franroav
    depends_on:
      - mongo_db
    # command: nx serve backend
    
    
volumes:
  mongo_db: {}
